version: '3.9'
services: 
    server:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        restart: always
        ports:
            - "3000:3000"
        environment:
            WAIT_HOSTS: database: 27017

    database:
        image: 'mongo'
        ports:
            - "27017:27017"
        env_file: 
            - .env
        environment: 
            MONGODB_USERNAME: 'rectangle'
            MONGODB_PASSWORD: 'mDMVXJ7XNwgRAI54'
